version: '2'
services:
  mariadb:
      image: 'bitnami/mariadb:10.1'
      volumes:
        - 'mariadb_data:/bitnami'
      secrets:
        - otb_database_name
        - otb_database_user
        - otb_database_password
        - otb_database_rootpass
      environment:
       MARIADB_ROOT_PASSWORD: /run/secrets/otb_database_rootpass
       MARIADB_USER: /run/secrets/otb_database_user
       MARIADB_PASSWORD: /run/secrets/otb_database_password
       MARIADB_DATABASE: /run/secrets/otb_database_name
  wordpress:
      image: 'bitnami/wordpress:4'
      volumes:
        - 'wordpress_data:/bitnami'
      depends_on:
        - mariadb
      secrets:
        - otb_database_name
        - otb_database_user
        - otb_database_password
        - otb_wordpress_user
        - otb_wordpress_pass
      environment:
       WORDPRESS_DATABASE_NAME: /run/secrets/otb_database_name
       WORDPRESS_DATABASE_USER: /run/secrets/otb_database_user
       WORDPRESS_DATABASE_PASSWORD: /run/secrets/otb_database_password
       WORDPRESS_USERNAME: /run/secrets/otb_wordpress_user
       WORDPRESS_PASSWORD: /run/secrets/otb_wordpress_pass
  wordpress-lb:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
      - ${public_port}:${public_port}
volumes:
  mariadb_data:
    driver: ${volume_driver}
  wordpress_data:
    driver: ${volume_driver}

secrets:
  otb_database_name:
    external: true
  otb_database_user:
    external: true
  otb_database_password:
    external: true
  otb_wordpress_user:
    external: true
  otb_wordpress_pass:
    external: true